# https://taskfile.dev

version: "3"

vars:
  COV_DATA: coverage.out

tasks:
  default:
    desc: List all available tasks
    silent: true
    internal: true
    cmds:
      - task --list

  tidy:
    desc: Tidy dependencies in go.mod and go.sum
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    cmds:
      - go mod tidy

  gen:
    desc: Run go generate
    sources:
      - "**/*.go"
    cmds:
      - go generate ./...

  fmt:
    desc: Run go fmt on all source files
    sources:
      - "**/*.go"
    cmds:
      - go fmt ./...

  test:
    desc: Run the test suite
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
      - "**/testdata/**/*"
    cmds:
      - go test -race ./... {{ .CLI_ARGS }}

  build:
    desc: Compile the project binary
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
      - .goreleaser.yml
    generates:
      - bin
      - dist
    cmds:
      - mkdir -p ./bin
      - goreleaser build --single-target --skip before --snapshot --clean --output ./bin/req

  bench:
    desc: Run all project benchmarks
    sources:
      - "**/*.go"
    cmds:
      - go test ./... -run None -benchmem -bench . {{ .CLI_ARGS }}

  lint:
    desc: Run the linters
    sources:
      - "**/*.go"
    preconditions:
      - sh: command -v golangci-lint
        msg: golangci-lint not installed, run `brew install golangci-lint`

      - sh: command -v typos
        msg: requires typos-cli, run `brew install typos-cli`

      - sh: command -v nilaway
        msg: requires nilaway, see https://github.com/uber-go/nilaway
    cmds:
      - golangci-lint run
      - typos
      - nilaway ./...

  cov:
    desc: Calculate test coverage and render the html
    generates:
      - "{{ .COV_DATA }}"
    cmds:
      - go test -race -cover -covermode atomic -coverprofile {{ .COV_DATA }} ./...
      - go tool cover -html {{ .COV_DATA }}

  check:
    desc: Run tests and linting in one
    cmds:
      - task: test
      - task: lint

  sloc:
    desc: Print lines of code
    cmds:
      - fd . -e go | xargs wc -l | sort -nr | head

  clean:
    desc: Remove build artifacts and other clutter
    cmds:
      - go clean ./...
      - rm -rf {{ .COV_DATA }}

  install:
    desc: Install the project on your machine
    deps:
      - uninstall
      - build
    cmds:
      - cp ./bin/req $GOBIN/req

  uninstall:
    desc: Uninstall the project from your machine
    cmds:
      - rm -rf $GOBIN/req

  update:
    desc: Updates dependencies in go.mod and go.sum
    cmds:
      - go get -u ./...
      - go mod tidy
