// Code generated by "stringer -type Kind -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[Error-1]
	_ = x[Comment-2]
	_ = x[Text-3]
	_ = x[Number-4]
	_ = x[URL-5]
	_ = x[Ident-6]
	_ = x[RequestSeparator-7]
	_ = x[At-8]
	_ = x[Eq-9]
	_ = x[Colon-10]
	_ = x[HTTPVersion-11]
	_ = x[MethodGet-12]
	_ = x[MethodHead-13]
	_ = x[MethodPost-14]
	_ = x[MethodPut-15]
	_ = x[MethodDelete-16]
	_ = x[MethodConnect-17]
	_ = x[MethodPatch-18]
	_ = x[MethodOptions-19]
	_ = x[MethodTrace-20]
}

const _Kind_name = "EOFErrorCommentTextNumberURLIdentRequestSeparatorAtEqColonHTTPVersionMethodGetMethodHeadMethodPostMethodPutMethodDeleteMethodConnectMethodPatchMethodOptionsMethodTrace"

var _Kind_index = [...]uint8{0, 3, 8, 15, 19, 25, 28, 33, 49, 51, 53, 58, 69, 78, 88, 98, 107, 119, 132, 143, 156, 167}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
