// Code generated by "stringer -type Kind -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[Error-1]
	_ = x[Comment-2]
	_ = x[Text-3]
	_ = x[Ident-4]
	_ = x[RequestSeparator-5]
	_ = x[At-6]
	_ = x[Eq-7]
	_ = x[MethodGet-8]
	_ = x[MethodHead-9]
	_ = x[MethodPost-10]
	_ = x[MethodPut-11]
	_ = x[MethodDelete-12]
	_ = x[MethodConnect-13]
	_ = x[MethodPatch-14]
	_ = x[MethodOptions-15]
	_ = x[MethodTrace-16]
}

const _Kind_name = "EOFErrorCommentTextIdentRequestSeparatorAtEqMethodGetMethodHeadMethodPostMethodPutMethodDeleteMethodConnectMethodPatchMethodOptionsMethodTrace"

var _Kind_index = [...]uint8{0, 3, 8, 15, 19, 24, 40, 42, 44, 53, 63, 73, 82, 94, 107, 118, 131, 142}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
