// Code generated by "stringer -type Kind -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[Error-1]
	_ = x[Comment-2]
	_ = x[Text-3]
	_ = x[RequestSeparator-4]
	_ = x[MethodGet-5]
	_ = x[MethodHead-6]
	_ = x[MethodPost-7]
	_ = x[MethodPut-8]
	_ = x[MethodDelete-9]
	_ = x[MethodConnect-10]
	_ = x[MethodPatch-11]
	_ = x[MethodOptions-12]
	_ = x[MethodTrace-13]
}

const _Kind_name = "EOFErrorCommentTextRequestSeparatorMethodGetMethodHeadMethodPostMethodPutMethodDeleteMethodConnectMethodPatchMethodOptionsMethodTrace"

var _Kind_index = [...]uint8{0, 3, 8, 15, 19, 35, 44, 54, 64, 73, 85, 98, 109, 122, 133}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
